### PR TITLE
GUI Changes to allow an account ID to be set for Cloud Sites clients

### PR DESCRIPTION
**Pull request by TJM**
These changes allow for an accountId to be specified to allow for editing of our client's DNS domains in Cloud Sites. Basically it has to change the DNS Management URL on the fly, so it requires changes to the python-clouddns library. 

These changes are fairly significant, since they change the "pathing" of the application to include the accountId number. Since HTTP is not stateful, we have to send the accountId with every request (or possibly start some session tracking stuff). I have done some testing, and it seems to work nicely. You have to load my fork of the python-clouddns library to get functionality, but I wrapped it so that it would "fail gracefully" if you are using the "rackspace" version (until they pull my changes).

My python-clouddns: https://github.com/TommyTheKid/python-clouddns

My Short Install Doc: http://goo.gl/Az2NW

Tommy

### CODE REVIEW

**Comment by TJM** [comment]
I made an update that allows it to work without any changes to python-clouddns.

**Comment by major** [comment]
Let me take a gander at these patches and get back with you.

**Comment by TJM** [comment]
Only the one on master (accountId) is ready, but you are welcome to "checkout" the ApplyTemplates patch. The function is mostly there, but the GUI part still needs done. Open a domain, then append /applyTemplate to the URL. It will mock up the changes of applying the googleApps.json. If you POST to that same URL, it will make the additions. I still need to sort out how I am going to make it work in the GUI, and I would also like to make it do that it can apply more than just the one template. Also, i would like it to remove conflicting records (optionally?),so yea, it's not ready for production yet. :)

**Comment by TJM** [comment]
_CLOSING_ --- I have a much better idea!

**Pull request closed without merging**
